# Generated by Django 2.2.4 on 2022-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAA_App', '0003_auto_20220616_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
